const pool = require('../db');

const values = [
  { name: 'ACCEPTANCE', definition: 'to be accepted as I am', original_order: 1 },
  { name: 'ACCEPTANCE', definition: 'be accepted as I want to be', original_order: 2 },
  { name: 'ACCURACY', definition: 'to be correct in my opinions and beliefs', original_order: 3 },
  { name: 'ACHIEVEMENT', definition: 'to have important accomplishments', original_order: 4 },
  { name: 'ADVENTURE', definition: 'to have new and exciting experiences', original_order: 5 },
  { name: 'ART', definition: 'to appreciate or express myself in art (cooking)', original_order: 6 },
  { name: 'ART', definition: 'to appreciate or express myself with what I build', original_order: 7 },
  { name: 'ATTRACTIVENESS', definition: 'to be physically attractive', original_order: 8 },
  { name: 'AUTHORITY', definition: 'to be in charge of others', original_order: 9 },
  { name: 'AUTONOMY', definition: 'to be self-determined and independent', original_order: 10 },
  { name: 'BEAUTY', definition: 'to appreciate beauty around me', original_order: 11 },
  { name: 'BELONGING', definition: 'to have a sense of belonging, being part of', original_order: 12 },
  { name: 'CARING', definition: 'to take care of others', original_order: 13 },
  { name: 'CHALLENGE', definition: 'to take on difficult tasks and problems', original_order: 14 },
  { name: 'COMFORT', definition: 'to have a pleasant and comfortable life', original_order: 15 },
  { name: 'COMMITMENT', definition: 'to make enduring, meaningful commitments', original_order: 16 },
  { name: 'COMPASSION', definition: 'to feel and act on concern for others', original_order: 17 },
  { name: 'COMPLEXITY', definition: 'to embrace the intricacies of life', original_order: 18 },
  { name: 'COMPROMISE', definition: 'to be willing to give and take in reaching agreements', original_order: 19 },
  { name: 'CONTRIBUTION', definition: 'to make a lasting contribution in the world', original_order: 20 },
  { name: 'COOPERATION', definition: 'to work collaboratively with others', original_order: 21 },
  { name: 'COURAGE', definition: 'to be brave and strong in the face of adversity', original_order: 22 },
  { name: 'COURTESY', definition: 'to be considerate and polite toward others', original_order: 23 },
  { name: 'CREATIVITY', definition: 'to create new things or ideas', original_order: 24 },
  { name: 'CURIOSITY', definition: 'to seek out, experience, and learn new things', original_order: 25 },
  { name: 'DEPENDABILITY', definition: 'to be reliable and trustworthy', original_order: 26 },
  { name: 'DILIGENCE', definition: 'to be thorough and conscientious in whatever I do', original_order: 27 },
  { name: 'DUTY', definition: 'to carry out my duties and obligations', original_order: 28 },
  { name: 'ECOLOGY', definition: 'to live in harmony with the environment', original_order: 29 },
  { name: 'EXCITEMENT', definition: 'to have a life full of thrills and stimulation', original_order: 30 },
  { name: 'FAITHFULNESS', definition: 'to be loyal and true in relationships', original_order: 31 },
  { name: 'FAME', definition: 'to be known and recognized', original_order: 32 },
  { name: 'FAMILY', definition: 'to have a happy, loving family', original_order: 33 },
  { name: 'FITNESS', definition: 'to be physically fit and strong', original_order: 34 },
  { name: 'FLEXIBILITY', definition: 'to adjust to new circumstances easily', original_order: 35 },
  { name: 'FORGIVENESS', definition: 'to be forgiving of others', original_order: 36 },
  { name: 'FREEDOM', definition: 'to be free from undue restrictions and limitations', original_order: 37 },
  { name: 'FRIENDSHIP', definition: 'to have close, supportive friends', original_order: 38 },
  { name: 'FUN', definition: 'to play and have fun', original_order: 39 },
  { name: 'GENEROSITY', definition: 'to give what I have to others', original_order: 40 },
  { name: 'GENUINENESS', definition: 'to act in a manner that is true to who I am', original_order: 41 },
  { name: "GOD'S WILL", definition: 'to seek and obey the will of God', original_order: 42 },
  { name: 'GRATITUDE', definition: 'to be thankful and appreciative', original_order: 43 },
  { name: 'GROWTH', definition: 'to keep changing and growing', original_order: 44 },
  { name: 'HEALTH', definition: 'to be physically well and healthy', original_order: 45 },
  { name: 'HONESTY', definition: 'to be honest and truthful', original_order: 46 },
  { name: 'HOPE', definition: 'to maintain a positive and optimistic outlook', original_order: 47 },
  { name: 'HUMILITY', definition: 'to be modest and unassuming', original_order: 48 },
  { name: 'HUMOR', definition: 'to see the humorous side of myself and the world', original_order: 49 },
  { name: 'IMAGINATION', definition: 'to have dreams and see possibilities', original_order: 50 },
  { name: 'INDEPENDENCE', definition: 'to be free from depending on others', original_order: 51 },
  { name: 'INDUSTRY', definition: 'to work hard and well at my life tasks', original_order: 52 },
  { name: 'INNER PEACE', definition: 'to experience personal peace', original_order: 53 },
  { name: 'INTEGRITY', definition: 'to live my daily life in a way that is consistent with my values', original_order: 54 },
  { name: 'INTELLIGENCE', definition: 'to keep my mind sharp and active', original_order: 55 },
  { name: 'INTIMACY', definition: 'to share my innermost experiences with others', original_order: 56 },
  { name: 'JUSTICE', definition: 'to promote fair and equal treatment for all', original_order: 57 },
  { name: 'KNOWLEDGE', definition: 'to learn and contribute valuable knowledge', original_order: 58 },
  { name: 'LEADERSHIP', definition: 'to inspire and guide others', original_order: 59 },
  { name: 'LEISURE', definition: 'to take time to relax and enjoy', original_order: 60 },
  { name: 'LOVED', definition: 'to be loved by those close to me', original_order: 61 },
  { name: 'LOVING', definition: 'to give love to others', original_order: 62 },
  { name: 'MASTERY', definition: 'to be competent in my everyday activities', original_order: 63 },
  { name: 'MINDFULNESS', definition: 'to live conscious and mindful of the present moment', original_order: 64 },
  { name: 'MODERATION', definition: 'to avoid excesses and find a middle ground', original_order: 65 },
  { name: 'MUSIC', definition: 'to enjoy or express myself in music', original_order: 66 },
  { name: 'NOVELTY', definition: 'to have a life full of change and variety', original_order: 67 },
  { name: 'OPENNESS', definition: 'to be open to new experiences, ideas, and options', original_order: 68 },
  { name: 'MONOGAMY', definition: 'to have one close, loving relationship', original_order: 69 },
  { name: 'NON-CONFORMITY', definition: 'to question and challenge authority and norms', original_order: 70 },
  { name: 'NURTURANCE', definition: 'to encourage and support others', original_order: 71 },
  { name: 'ORDER', definition: 'to have a life that is well-ordered and organized', original_order: 72 },
  { name: 'PASSION', definition: 'to have deep feelings about ideas, activities, or people', original_order: 73 },
  { name: 'PLEASURE', definition: 'to feel good', original_order: 74 },
  { name: 'POWER', definition: 'to have control over others', original_order: 75 },
  { name: 'PROTECT', definition: 'to protect and keep safe those I love', original_order: 76 },
  { name: 'PURPOSE', definition: 'to have meaning and direction in my life', original_order: 77 },
  { name: 'PATRIOTISM', definition: 'to love, serve, and protect my country', original_order: 78 },
  { name: 'POPULARITY', definition: 'to be well-liked by many people', original_order: 79 },
  { name: 'PRACTICALITY', definition: 'to focus on what is practical, prudent, and sensible', original_order: 80 },
  { name: 'PROVIDE', definition: 'to provide for and take care of my family', original_order: 81 },
  { name: 'RATIONALITY', definition: 'to be guided by reason, logic, and evidence', original_order: 82 },
  { name: 'REALISM', definition: 'to see and act realistically and practically', original_order: 83 },
  { name: 'RESPONSIBILITY', definition: 'to make and carry out responsible decisions', original_order: 84 },
  { name: 'RISK', definition: 'to take risks and chances', original_order: 85 },
  { name: 'ROMANCE', definition: 'to have intense, exciting love in my life', original_order: 86 },
  { name: 'SAFETY', definition: 'to be safe and secure', original_order: 87 },
  { name: 'SELF-ACCEPTANCE', definition: 'to accept myself as I am', original_order: 88 },
  { name: 'SELF-CONTROL', definition: 'to be disciplined in my own actions', original_order: 89 },
  { name: 'SELF-ESTEEM', definition: 'to feel good about myself', original_order: 90 },
  { name: 'SELF-KNOWLEDGE', definition: 'to have a deep and honest understanding of myself', original_order: 91 },
  { name: 'SERVICE', definition: 'to be helpful and of service to others', original_order: 92 },
  { name: 'SEXUALITY', definition: 'to have an active and satisfying sex life', original_order: 93 },
  { name: 'SOLITUDE', definition: 'to have time and space where I can be apart from others', original_order: 94 },
  { name: 'STABILITY', definition: 'to have a life that stays fairly consistent', original_order: 95 },
  { name: 'TRADITION', definition: 'to follow respected patterns of the past', original_order: 96 },
  { name: 'WEALTH', definition: 'to have enough money to not have financial worries', original_order: 97 },
  { name: 'WEALTH', definition: 'to have plenty of money', original_order: 98 },
  { name: 'SIMPLICITY', definition: 'to live life simply, with minimal needs', original_order: 99 },
  { name: 'SPIRITUALITY', definition: 'to grow and mature spiritually', original_order: 100 },
  { name: 'TOLERANCE', definition: 'to accept and respect those who differ from me', original_order: 101 },
  { name: 'VIRTUE', definition: 'to live a morally pure and excellent life', original_order: 102 },
  { name: 'WORLD PEACE', definition: 'to work to promote peace in the world', original_order: 103 },
  { name: 'APPRECIATION', definition: 'my accomplishments are appreciated', original_order: 104 },
  { name: 'ACCOMPLISHMENT', definition: 'excel at whatever I do', original_order: 105 },
  { name: 'QUALITY', definition: 'expect/deliver high quality', original_order: 106 },
  { name: 'MERIT', definition: 'be judged by what I do, not what I say', original_order: 107 },
];

async function seed() {
  for (const v of values) {
    await pool.query(
      'INSERT INTO values_list (name, definition, original_order) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING',
      [v.name, v.definition, v.original_order]
    );
  }
  console.log('Seed complete');
  await pool.end();
}

seed().catch(err => {
  console.error('Seed failed:', err);
  process.exit(1);
});
